.PHONY: all clean cleanall

all:
	$(MAKE) -C tinyPTC
	$(MAKE) -C picoPNG

clean:
	$(MAKE) -C picoPNG clean
	$(MAKE) -C tinyPTC clean

cleanall:
	$(MAKE) -C picoPNG cleanall
	$(MAKE) -C tinyPTC cleanall